spring.application.name=gamestore

##Configurar o Banco de Dados
spring.datasource.url=jdbc:postgresql://d6tvgvbuibrs73epl8mg-a.oregon-postgres.render.com/db_deploy_gs_ortegaalice
spring.datasource.username=db_deploy_gs_ortegaalice_user
spring.datasource.password=LQ2cDfBK0ZBtAQb0nIgyrMipYpIsqayf
# obs: nunca colocar senhas em documentos que vão para o github

## Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
